/*
 * This source file was generated by the Gradle 'init' task
 */
package javagradle2;

import org.junit.jupiter.api.Test;

import javagradle2.Calculator;

import static org.junit.jupiter.api.Assertions.*;

public class CalculatorTest {
    
    private Calculator calc = new Calculator();
    
    @Test
    public void testAdd() {
        assertEquals(15, calc.add(10, 5));
        assertEquals(0, calc.add(-5, 5));
    }
    
    @Test
    public void testSubtract() {
        assertEquals(5, calc.subtract(10, 5));
        assertEquals(-15, calc.subtract(-10, 5));
    }
    
    @Test
    public void testMultiply() {
        assertEquals(50, calc.multiply(10, 5));
        assertEquals(0, calc.multiply(0, 5));
    }
    
    @Test
    public void testDivide() {
        assertEquals(2, calc.divide(10, 5));
        assertThrows(ArithmeticException.class, () -> calc.divide(10, 0));
    }
}